<?= create_BreadCrumbs('account/', 'Thông tin đăng ký') ?>
<div class="main_fix my-5">
	<h1><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Chào mừng bạn đến với CKD – Nền tảng Mua sắm Trực tuyến của CKD VIỆT NAM!</span></span></span></span></span></span></span></h1>

	<h3 style="line-height: 1.38; margin-top: 24px; margin-bottom: 8px;"><strong><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Làm thế nào để nhận ưu đãi?</span></span></span></span></span></span></span></strong></h3>

	<ul>
		<li aria-level="1" style="list-style-type:none"><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Việc đầu tiên để nhận ưu đãi là đăng ký thành viên tại website CKD. Quá trình đăng ký đơn giản và nhanh chóng, chỉ mất vài bước.</span></span></span></span></span></span></span></li>
		<li aria-level="1" style="list-style-type:none"><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Hoàn thành thông tin cá nhân: Sau khi đăng ký, hãy hoàn thành thông tin cá nhân của bạn để chúng tôi có thể cập nhật những ưu đãi và thông báo mới nhất đến bạn.</span></span></span></span></span></span></span></li>
		<li aria-level="1" style="list-style-type:none"><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Nhập mã voucher khi thanh toán: Khi bạn chọn sản phẩm yêu thích và đi đến trang thanh toán, voucher sẽ hiển thị ở phần dưới nút thanh toán.</span></span></span></span></span></span></span></li>
	</ul>

	<p style="line-height:2.057142857142857; text-align:justify; background-color:#ffffff; padding:0pt 0pt 8pt 0pt"><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#000000"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">Quyền lợi khi trở thành thành viên của CKD?</span></span></span></span></span></span></span></p>

	<p style="line-height:2.057142857142857; text-align:justify; background-color:#ffffff; padding:0pt 0pt 8pt 0pt"><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#ea8025"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">Ưu đãi 10% với bước đăng ký thành viên nhanh chóng, chính là món quà dành riêng cho các thành viên mới của CKD Việt Nam !</span></span></span></span></span></span></span></p>

	<p style="line-height:2.057142857142857; text-align:justify; background-color:#ffffff; padding:0pt 0pt 8pt 0pt"><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#000000"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">chỉ cần </span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#ea8025"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">tích chọn đăng ký</span></span></span></span></span><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#000000"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none"> trên website ckdvietnam.com, bạn sẽ nhận được ưu đãi 10% cho lần mua sản phẩm đầu tiên. <a href="https://ckdvietnam.com/account/dang-ky"><u>Đăng ký ngay</u></a></span></span></span></span></span></span></span></p>

	<p style="line-height: 2.05714; background-color: rgb(255, 255, 255); padding: 0pt 0pt 8pt; text-align: center;"><img alt="" src="https://ckdvietnam.com/upload/elfinder/C%E1%BA%A8M%20NANG/cam%20nang/dang-ky-thanh-vien.webp" /></p>

	<p style="line-height:2.057142857142857; text-align:justify; background-color:#ffffff; padding:0pt 0pt 8pt 0pt"><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#000000"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">(*) Mỗi khách hàng chỉ được áp dụng mã 1 lần (sử dụng duy nhất một tài khoản đăng ký). CKD xin phép từ chối áp dụng ưu đãi cho các trường hợp có dấu hiệu gian lận, không hợp lệ. </span></span></span></span></span></span></span></p>

	<p style="line-height:2.057142857142857; text-align:justify; background-color:#ffffff; padding:0pt 0pt 8pt 0pt"><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Bạn sẽ còn nhận thêm rất nhiều quyền lợi và ưu đãi dài hạn khi trở thành thành viên của CKD, khám phá ngay nhé! </span></span></span></span></span></span></span></p>

	<p style="line-height:2.057142857142857; text-align:justify; background-color:#ffffff; padding:0pt 0pt 8pt 0pt"><strong><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Tại sao nên chọn CKD?</span></span></span></span></span></span></span></strong></p>

	<ul>
		<li aria-level="1" style="list-style-type:none"><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Thấu hiểu được làn da bạn: Tại CKD, chúng tôi tự hào cung cấp các sản phẩm chất lượng lượng, từ nghiên cứu thành phần, điều chế sản phẩm sau đó  thông qua các viện nghiên cứu, thử nghiệm trực tiếp trên người và sau đó mới đến tay người tiêu dùng để đảm bảo tính an toàn và hiệu quả nhất. Bạn có thể tìm thấy các sản phẩm chăm sóc da, cơ thể,  </span></span></span></span></span><a href="https://ckdvietnam.com/san-pham"><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#000000"><span style="font-weight:700"><span style="font-style:normal"><span style="text-decoration:none">ở đây</span></span></span></span></span></a><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">. Điều đặc biệt chúng tôi luôn ưu tiên và đặt khách hàng trên hết</span></span></span></span></span></span></span></li>
		<li aria-level="1" style="list-style-type:none"> </li>
		<li aria-level="1" style="list-style-type:none"><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Giao hàng nhanh chóng: Với hệ thống vận chuyển hiện đại, chúng tôi đảm bảo đơn hàng của bạn sẽ đến tay bạn một cách an toàn và nhanh chóng.</span></span></span></span></span></span></span></li>
	</ul>

	<h2 style="line-height:1.38; margin-top:24px; margin-bottom:8px"><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Thời gian ưu đãi có hạn đừng bỏ lỡ nhé! – <a href="https://ckdvietnam.com/account/dang-ky">Đăng ký ngay!</a></span></span></span></span></span></span></span></h2>

	<p style="line-height:1.38"><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Đừng hỏi trend mới thị trường sài hoạt chất gì hot, hãy hỏi làn da bạn cần gì lúc này ! đăng ký thành viên ngay hôm nay để nhận voucher 10% và hàng ngàn voucher ưu đãi khác, thả ga mua sắm trực tuyến.</span></span></span></span></span></span></span></p>

	<p> </p>

	<p style="line-height:1.38"><span style="font-size:16px;"><span style="font-family:Arial,Helvetica,sans-serif;"><span style="font-variant: normal; white-space: pre-wrap;"><span style="color:#000000"><span style="font-weight:400"><span style="font-style:normal"><span style="text-decoration:none">Chú ý: Ưu đãi chỉ áp dụng trong khoảng thời gian nhất định. CKD có quyền thay đổi điều kiện và điều khoản theo từng thời điểm phù hợp.</span></span></span></span></span></span></span></p>

	<p><br />
		 </p>

</div>
